#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely.
# Requirement: Add a sleep of 2 seconds between each iteration of the loop.
# Additionally, it traps SIGTERM to display 'I am invincible!!!' when terminated.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
