#!/usr/bin/env bash
# This line specifies that the script should be interpreted using Bash.

# A loop that runs 10 times
for ((i = 1; i <= 10; i++))
do
    # This line will be executed in each iteration of the loop.
    # It prints the text "Best School" to the console.
    echo "Best School"
done
