#!/usr/bin/env bash

# Read each line of /etc/passwd
while IFS=: read -r username x userid x x x home_directory x; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home_directory"
done < /etc/passwd
