#!/usr/bin/env bash
# Check if the key pair already exists
if [[ -f school && -f school.pub ]]; then
    echo "RSA key pair 'school' already exists."
    exit 1
fi

# Generate RSA key pair
ssh-keygen -t rsa -b 4096 -f school -C "Generated RSA key pair for school" -N "betty"

if [[ $? -eq 0 ]]; then
    echo "RSA key pair 'school' created successfully."
    ls -l school*
else
    echo "Failed to create RSA key pair 'school'."
fi

